name: Build and Release

on:
  push:
    branches:
      - initial

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Build for Linux
        run: go build -o initz_linux 

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o initz_windows.exe 

      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            ./initz_linux
            ./initz_windows.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: ./binaries

      - name: Create Release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.3.0-alpha-2
          release_name: Release v0.3.0-alpha-2
          body: |
            Release description goes here.
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        if: success()
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: ./binaries/initz_linux
          asset_name: initz_linux
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        if: success()
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: ./binaries/initz_windows.exe
          asset_name: initz_windows.exe
          asset_content_type: application/octet-stream
